# Generated by Django 4.2.3 on 2023-08-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0003_zodiac_number_alter_zodiac_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiac',
            name='element',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Water', 'Water'), ('Earth', 'Earth'), ('Air', 'Air')], default='Fire', max_length=5),
        ),
    ]
